### ISSUE TITLE
Create Register Component

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/undecided#4]
<img width="838" alt="image" src="https://github.com/acm-ucr/undecided/assets/36285610/b65654df-2f72-46f5-9c6b-b1c4c734a5dd">

- components/register/Register
- Input component will be handled by someone else

**Comment by fardinzam** [comment]
I've finished all of my issues but my vscode isn't letting me push for some reason, it's telling me I'm signed into a different account (I'm not) and don't have access to push changes to this repo. I'll figure it out and push everything soon
