### ISSUE TITLE
Make Hollow Star

### ISSUE THREAD

**Issue by shahdivyank** [acm-ucr/undecided#41]
<img width="670" alt="image" src="https://github.com/acm-ucr/undecided/assets/36285610/728837f7-f898-4c37-8ae9-785db24723d0">

- Star should be hollow when not liked and then filled when liked
- Refer to other places in the code for implementation

**Comment by twang0323** [comment]
![image](https://github.com/acm-ucr/undecided/assets/122486013/08973ce7-b8ee-4ece-930a-b21a813f3312)
